[package]
name = "quickdry"
version = "0.1.1"
authors = ["Russell Johnston <rpjohnst@gmail.com>"]
edition = "2018"
description = "Bump-pointer arena allocator"
repository = "https://github.com/driveyard/driveyard"
readme = "README.md"
categories = ["memory-management"]
license = "MIT/Apache-2.0"
